In [ ]:
import numpy as np

In [ ]:
vectors = np.array(
    [[0, 0, 4],
     [0, 1, 1],
     [1, 1, 1]]
)

In [ ]:
q1 = vectors[0]

In [ ]:
q1_normalized = q1/np.linalg.norm(q1)
q1_normalized

array([0., 0., 1.])

In [ ]:
basis = []
basis.append(q1_normalized)

In [ ]:
q2 = vectors[1] - np.dot(q1_normalized, vectors[1]) * q1_normalized
if np.linalg.norm(q2) < 1e-7:
  print("q2 is dependent on q1")
else:
    q2_normalized = q2/np.linalg.norm(q2)
    basis.append(q2_normalized)
    q2_normalized

In [ ]:
q2_normalized

array([0., 1., 0.])

In [ ]:
basis

[array([0., 0., 1.]), array([0., 1., 0.])]

In [ ]:
q3 = vectors[2] - \
 np.dot(q1_normalized, vectors[2]) * q1_normalized - \
 np.dot(q2_normalized, vectors[2]) * q2_normalized

if np.linalg.norm(q3) < 1e-7:
  print("q3 is dependent on q1")
else:
    q3_normalized = q3/np.linalg.norm(q3)
    basis.append(q3_normalized)
    q3_normalized

In [ ]:
q3_normalized

array([1., 0., 0.])

In [ ]:
def  gram_schmidt(vectors):
  basis = []
  for ai in vectors:
    qnew = ai - np.sum( np.dot(ai,qj) * qj for qj in basis)
    norm = np.linalg.norm(qnew)
    if (norm > 1e-10):
      basis.append(qnew/norm)
    else:
      raise Exception(f )
  return np.array(basis)


In [ ]:
gram_schmidt(vectors)

<ipython-input-12-5445c5e0b300>:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  qnew = ai - np.sum( np.dot(ai,qj) * qj for qj in basis)


array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
vectors = np.array(
    [[0, 0, 4],
     [0, 0, 2],
     [1, 1, 1]])
gram_schmidt(vectors)

<ipython-input-12-5445c5e0b300>:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  qnew = ai - np.sum( np.dot(ai,qj) * qj for qj in basis)


array([[0., 0., 1.]])